### ISSUE TITLE
About stub animation breaks last paragraph line

### ISSUE THREAD

**Issue by neilitalia** [rileyjshaw/rileyjshaw.github.io#5] opened 2020-01-19 01:01 UTC
![ezgif-3-95eadf2d7777](https://user-images.githubusercontent.com/38524171/72672693-9ec1f880-3a23-11ea-97d1-df45e68a213c.gif)

I think this is caused by the Narrow No-Break Space character (U+202F) before the Heavy North East Arrow (U+279A) in styling ``a[target="_blank"]::after``

While tweaking on Firefox Devtools, I found that this might be remedied by changing
```
a[target="_blank"]::after {
    content: "\202F\279A";
    font-family: var(--font-stack-serif);
}
```

to just
```
a[target="_blank"]::after {
    content: "\279A";
    font-family: var(--font-stack-serif);
}
```

I'm running Mozilla Firefox 72.0.1 (64-bit) on Windows 10 at 1920x1080

**Comment by rileyjshaw** [comment] 2020-01-23 00:51
Thank you for noticing this and reporting an issue!

I decided to keep the Narrow No-Break Space, and change a few other things about how lines are wrapped. I also enforced a specific width on the `CycleText` component, since it shouldn't be affecting layout.

This issue is (hopefully) fixed in https://github.com/rileyjshaw/rileyjshaw.github.io/commit/aa170e91aa8bc180f08c9ceb72060e215fcee931, but please let me know if you can still reproduce the bug. Thanks again!

**Closed as completed by rileyjshaw** 2020-01-23 00:51 UTC
